config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :groups do
    resources :messages
  end
  root 'messages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  accepts_nested_attributes_for :group_users

  validate :add_error_name_empty

  private

  def add_error_name_empty
    if name.empty?
      errors[:base] << "グループ名を入力してください。"
    end
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(create_params)
    if @group.save
      flash[:notice] = 'チャットグループが作成されました。'
      redirect_to root_path
    else
      flash.now[:alert] = 'チャットグループが作成されませんでした。'
      render :new
    end
  end

  def edit
  end

  def update
    @group.update(create_params)
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def create_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @group = current_user.groups.first
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = Message.new(create_params)
    if @message.save
      flash[:notice] = 'メッセージ送信成功。'
    else
      flash[:alert] = 'メッセージが空です。'
    end
    redirect_to group_messages_path
  end

  private

  def create_params
    params.require(:message).permit(:body).merge(group_id: params[:group_id], user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_group-form.html.haml
- if @group.errors.any?
  .chat-group-form__errors
    %h2<
      = @group.errors.count
      = "件のエラーが発生しました。"
    %ul
      - @group.errors.full_messages.each do |msg|
        %li<
          = msg
= form_for @group do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :グループ名, class: "chat-group-form__label", for: "group_name"
    .chat-group-form__field--right
      = f.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー, class: "chat-group-form__label", for: "group_user_ids"
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        = f.collection_check_boxes :user_ids, User.all, :id, :name do |b|
          = b.label{b.check_box + b.text}
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "Save", class: "chat-group-form__action-btn"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: "group-form"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: "group-form"

app/views/layouts/application.html.haml
!!!
%html{lang: "ja"}
  %head
    %meta{charset: "UTF-8"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: "shared/notification"
    = yield

app/views/messages/_body-message.html.haml
.body-message
  - messages.each do |message|
    %p.body-message__name<
      = message.user.name
    %p.body-message__time<
      = message.created_at
    %p.body-message__body<
      = message.body

app/views/messages/_side-group.html.haml
.side-group
  %p.side-group__name<
    group name
  %p.side-group__message<
    group message

app/views/messages/index.html.haml
= render partial: "shared/chat-side"

.chat-main
  .chat-main__header
    .chat-main__header-group
      %p.chat-main__header-group-name<
        = @group.name
      = link_to "edit", "/groups/#{@group.id}/edit", class: "chat-main__header-group-edit-btn"
    .chat-main__header-members<
      MEMBER:
      - @group.users.each do |user|
        %i<
          = user.name
  .chat-main__body
    .chat-main__body-messages-list
      = render partial: "body-message", locals: { messages: @messages }
  .chat-main__footer
    = form_for [@group, @message], html: {class: "chat-main__footer-form"} do |f|
      .chat-main__footer-body
        = f.text_field :body, class: "chat-main__footer-body-message", placeholder: "type a message"
        = f.submit "Send", class: "chat-main__footer-body-submit"

app/views/shared/_chat-side.html.haml
.chat-side
  .chat-side__user
    .chat-side__user-content
      %p.chat-side__user-name<
        user name
      %a.chat-side__user-new-group
        %i.fa.fa-pencil-square-o
      %a.chat-side__user-edit
        %i.fa.fa-cog
  .chat-side__groups
    .chat-side__groups-list
      = render partial: "side-group"

app/views/shared/_notification.html.haml
- flash.each do |key, value|
  - key = "info" if key == "notice"
  - key = "danger" if key == "alert"
  = content_tag :p, value, class: "alert alert-#{key} notification"